### PR TITLE
Document generics order for PriorityQueue and SplPriorityQueue

### LINKED ISSUE #71: `PriorityQueue` generics do not align with `SplPriorityQueue`
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.12.0

#### Summary

In one of the older releases, generics were added for the `PriorityQueue`.
I've updated to that and also got psalm bitching about `SplPriorityQueue`.
Now, since I want to fix both issues, I have to adapt different styles.

#### Current behavior

Generics for `PriorityQueue` needs to be written like:

`PriorityQueue<TValue,TPriority>`

Generics for `SplPriorityQueue` needs to be written like:
`SplPriorityQueue<TPriority,TValue>`

The latter feels more convenient, as its also aligned with arrays and keys. Since the priority queue is some kind of "array" as well, thats more inconvenient if I have to annotate the value as the key and the key as a value within the generic annotation in `PriorityQueue` implemetation.

#### How to reproduce

```php
use Laminas\Stdlib\PriorityQueue;
use SplPriorityQueue;

final class Foo
{
    /** @var PriorityQueue<non-empty-string,int> */
    public PriorityQueue $laminas;
   
    /** @var PriorityQueue<int, non-empty-string> */
    public SplPriorityQueue $php;


    public function addString(): void
    {
        $this->php->insert('foo', count($this->php->count());
        $this->laminas->insert('foo', count($this->laminas->count());
    }
}
```

#### Expected behavior

```php
use Laminas\Stdlib\PriorityQueue;
use SplPriorityQueue;

final class Foo
{
    /** @var PriorityQueue<int, non-empty-string> */
    public PriorityQueue $laminas;
   
    /** @var PriorityQueue<int, non-empty-string> */
    public SplPriorityQueue $php;


    public function addString(): void
    {
        $this->php->insert('foo', count($this->php->count());
        $this->laminas->insert('foo', count($this->laminas->count());
    }
}
```

### PR DESCRIPTION
**Pull request by gsteel**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | yes

Reference #71

Previously implemented template order did not match those of native SplPriorityQueue, i.e. \SplPriorityQueue<TPriority, TValue> - instead the templates were back-to-front.

It's decided that 'fixing' the order of the placeholders will be inconvenient for users that have already implemented templates with the existing order.

- PriorityQueue value template renamed from `T` to `TValue`
- Removes attempt to document internal array priority, adding resulting psalm issues to the baseline. Users will typically insert with an integer priority and shouldn't care that internally an array is used to represent priority - also, an array for \SplPriorityQueue priority is effectively an invalid argument according to stubs - this is better off in the baseline right?

### CODE REVIEW

**Comment by gsteel** [comment]
Not sure if this should target 3.12.1 or 3.13.0 ?

**Comment by Ocramius** [comment]
@gsteel if this is a bugfix, `3.12.x` IMO.

**Comment by boesing** [comment]
This would possibly break upstream projects which already spent time in fixing their code.

Yes, this looks correct to me but technically, it was not incorrect before.
Do we really want introduce this in a Patch?

**Comment by boesing** [comment]
ah this is only released for a few hours, maybe we can Patch it 👌🏻

**Comment by gsteel** [comment]
Generics were introduced and released in #58 and #59 back in June

**Comment by boesing** [comment]
Oh, thats been a while. Not sure if we should annoy upstream devs who spent time to fix their static analysis. Do we have other thoughts?

**Comment by gsteel** [comment]
> Not sure if we should annoy upstream devs who spent time to fix their static analysis

I guess it depends whether we consider the original template order a bug or not - IMO it's a bug - aligning with PHP's SplPriorityQueue and psalms stubs should be a given. Not annoying devs with this is really valid, but the longer it's left, the more people we annoy?

This will already affect one or two laminas packages I think… view, maybe validator, possibly others. My bad! Sorry…

**Comment by internalsystemerror** [comment]
> Oh, thats been a while. Not sure if we should annoy upstream devs who spent time to fix their static analysis. Do we have other thoughts?

It's also possible, if this is a bug, that devs who already implemented correct static analysis have been annoyed by this break, so would appreciate this fix.

**Comment by Ocramius** [comment]
Discussed in chat: clarifying template types is OK, but swapping order will likely just lead to unnecessary downstream breakages.

Yes, it is annoying that the generic types are inverted in our implementation, but it is just that: annoying. Not a major deal breaker.

**Review by Ocramius — APPROVED** [review]
:ship:

**Pull request merged**
