### PR TITLE
Update require php to ~8.4.0

### PR DESCRIPTION
**Pull request by raphaelstolt**
Makes the laminas-stdlib available for PHP 8.4.

### CODE REVIEW

**Comment by gsteel** [comment]
8.4 is not yet available in CI. The supported range won't be updated until we can verify that all tests pass on 8.4

**Comment by raphaelstolt** [comment]
It's available.

**Comment by gsteel** [comment]
> It's available.

Show me in the checks below where this lib was tested on 8.4

**Comment by raphaelstolt** [comment]
I can just link a GitHub Actions [job](https://github.com/raphaelstolt/lean-package-validator/actions/runs/10088873420/job/27895342209) where PHP 8.4 is successfully installed, so generally it's available.

**Comment by Ocramius** [comment]
Needs to be in:

 * https://github.com/laminas/laminas-ci-matrix-action
 * https://github.com/laminas/laminas-continuous-integration-action

**Comment by fezfez** [comment]
@raphaelstolt  the issue seem to be adressed, can you run the ci again

**Comment by Ocramius** [comment]
Needs adjusting 😁

Probably need to ignore platform requirements on PHP 8.4

**Comment by nishant04412** [comment]
Are we waiting for [vemio/psalm](https://github.com/vimeo/psalm/pull/10928) PR with PHP 8.4 support to get merged for this to unblock ?

**Comment by gsteel** [comment]
Thanks for your help here @raphaelstolt but this has been implemented in #119

**Pull request closed without merging**
